[project]
name = "yggdrasil"
version = "2.0.0"
description = "Base components for Saebasol projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
style = [
    "ruff>=0.13.1",
]
test = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-cov>=7.0.0",
]
type = [
    "mypy>=1.18.2",
    "pyright>=1.1.405",
]
dev = [
    "asyncpg>=0.30.0",
    "aiohttp>=3.12.15",
    "pymongo>=4.15.1",
    "pythonmonkey>=1.2.0",
    "sqlalchemy>=2.0.43",
]

[project.optional-dependencies]
infrastructure = [
    "asyncpg>=0.30.0",
    "aiohttp>=3.12.15",
    "pymongo>=4.15.1",
    "pythonmonkey>=1.2.0",
    "sqlalchemy>=2.0.43",
]

[tool.pyright]
include = ["yggdrasil"]
typeCheckingMode = "strict"

[tool.ruff]
include = ["yggdrasil/**/*.py"]
lint.extend-select = ["I"]
lint.select = []

[tool.mypy]
packages = ["yggdrasil"]
disable_error_code = ["attr-defined", "union-attr", "name-defined", "used-before-def", "call-arg", "arg-type", "call-overload", "valid-type", "var-annotated", "override", "return", "empty-body", "return-value", "assignment", "method-assign", "type-var", "operator", "index", "list-item", "dict-item", "typeddict-item", "typeddict-unknown-key", "has-type", "import", "no-redef", "func-returns-value", "abstract", "type-abstract", "safe-super", "valid-newtype", "exit-return", "name-match", "literal-required", "no-overload-impl", "unused-coroutine", "top-level-await", "assert-type", "truthy-function", "str-format", "str-bytes-safe", "annotation-unchecked", "syntax", "misc"]
disallow_untyped_defs = true

[tool.setuptools.packages.find]
where = ["."]
include = ["yggdrasil*"]

[build-system]
requires = ["setuptools>=72.0"]
build-backend = "setuptools.build_meta"
